development:
  adapter: postgresql
  encoding: unicode
  database: oneayear_dev
  pool: 5
  username: brentvatne
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: oneayear_test
  pool: 5
  username: brentvatne
  password:
